# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import my_uber_pb2 as my__uber__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in my_uber_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaxiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTaxi = channel.unary_unary(
                '/my_uber.TaxiService/RegisterTaxi',
                request_serializer=my__uber__pb2.TaxiInfo.SerializeToString,
                response_deserializer=my__uber__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.UpdatePosition = channel.unary_unary(
                '/my_uber.TaxiService/UpdatePosition',
                request_serializer=my__uber__pb2.Position.SerializeToString,
                response_deserializer=my__uber__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.AssignService = channel.unary_unary(
                '/my_uber.TaxiService/AssignService',
                request_serializer=my__uber__pb2.Empty.SerializeToString,
                response_deserializer=my__uber__pb2.ServiceAssignment.FromString,
                _registered_method=True)


class TaxiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterTaxi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaxiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTaxi': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterTaxi,
                    request_deserializer=my__uber__pb2.TaxiInfo.FromString,
                    response_serializer=my__uber__pb2.RegistrationResponse.SerializeToString,
            ),
            'UpdatePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePosition,
                    request_deserializer=my__uber__pb2.Position.FromString,
                    response_serializer=my__uber__pb2.UpdateResponse.SerializeToString,
            ),
            'AssignService': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignService,
                    request_deserializer=my__uber__pb2.Empty.FromString,
                    response_serializer=my__uber__pb2.ServiceAssignment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'my_uber.TaxiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('my_uber.TaxiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaxiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterTaxi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/my_uber.TaxiService/RegisterTaxi',
            my__uber__pb2.TaxiInfo.SerializeToString,
            my__uber__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/my_uber.TaxiService/UpdatePosition',
            my__uber__pb2.Position.SerializeToString,
            my__uber__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/my_uber.TaxiService/AssignService',
            my__uber__pb2.Empty.SerializeToString,
            my__uber__pb2.ServiceAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
