# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: my_uber.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'my_uber.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmy_uber.proto\x12\x07my_uber\"k\n\x08TaxiInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06grid_n\x18\x02 \x01(\x05\x12\x0e\n\x06grid_m\x18\x03 \x01(\x05\x12\x11\n\tinitial_x\x18\x04 \x01(\x05\x12\x11\n\tinitial_y\x18\x05 \x01(\x05\x12\r\n\x05speed\x18\x06 \x01(\x05\"1\n\x08Position\x12\x0f\n\x07taxi_id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\"\'\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x0eUpdateResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\"%\n\x11ServiceAssignment\x12\x10\n\x08\x61ssigned\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xd0\x01\n\x0bTaxiService\x12\x42\n\x0cRegisterTaxi\x12\x11.my_uber.TaxiInfo\x1a\x1d.my_uber.RegistrationResponse\"\x00\x12>\n\x0eUpdatePosition\x12\x11.my_uber.Position\x1a\x17.my_uber.UpdateResponse\"\x00\x12=\n\rAssignService\x12\x0e.my_uber.Empty\x1a\x1a.my_uber.ServiceAssignment\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_uber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAXIINFO']._serialized_start=26
  _globals['_TAXIINFO']._serialized_end=133
  _globals['_POSITION']._serialized_start=135
  _globals['_POSITION']._serialized_end=184
  _globals['_REGISTRATIONRESPONSE']._serialized_start=186
  _globals['_REGISTRATIONRESPONSE']._serialized_end=225
  _globals['_UPDATERESPONSE']._serialized_start=227
  _globals['_UPDATERESPONSE']._serialized_end=261
  _globals['_SERVICEASSIGNMENT']._serialized_start=263
  _globals['_SERVICEASSIGNMENT']._serialized_end=300
  _globals['_EMPTY']._serialized_start=302
  _globals['_EMPTY']._serialized_end=309
  _globals['_TAXISERVICE']._serialized_start=312
  _globals['_TAXISERVICE']._serialized_end=520
# @@protoc_insertion_point(module_scope)
